apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\allan\AppData\Local\Microsoft\WinGet\Links\kompose.exe convert -f docker-compose.yaml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: backend
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\allan\AppData\Local\Microsoft\WinGet\Links\kompose.exe convert -f docker-compose.yaml
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: backend
    spec:
      containers:
        - env:
            - name: SPRING_DATA_MONGODB_URI
              value: mongodb://mongo:27017/infraopsdb
          image: ghcr.io/allanbikundo/backend:latest
          name: backend
          ports:
            - containerPort: 8081
              protocol: TCP
      restartPolicy: Always
