apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\allan\AppData\Local\Microsoft\WinGet\Links\kompose.exe convert -f docker-compose.yaml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: frontend
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\allan\AppData\Local\Microsoft\WinGet\Links\kompose.exe convert -f docker-compose.yaml
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: frontend
    spec:
      containers:
        - image: ghcr.io/allanbikundo/frontend:latest
          name: frontend
          ports:
            - containerPort: 80
              protocol: TCP
      restartPolicy: Always
