apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\allan\AppData\Local\Microsoft\WinGet\Links\kompose.exe convert -f docker-compose.yaml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  type: NodePort
  ports:
    - name: "3000"
      port: 3000
      targetPort: 80
      nodePort: 30002 # Specify the NodePort (optional, or let Kubernetes auto-assign)
  selector:
    io.kompose.service: frontend