apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\allan\AppData\Local\Microsoft\WinGet\Links\kompose.exe convert -f docker-compose.yaml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: mongo
  name: mongo
spec:
  type: NodePort
  ports:
    - name: "27017"
      port: 27017
      targetPort: 27017
      nodePort: 30003 # Specify the NodePort (optional, or let Kubernetes auto-assign)
  selector:
    io.kompose.service: frontend
