name: Build and Push Backend and Frontend Images

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to GitHub Container Registry (GHCR)
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Step 3: Build and Push Backend Image
      - name: Build and push backend image
        run: |
          docker build -t ghcr.io/allanbikundo/backend:latest ./backend
          docker tag ghcr.io/allanbikundo/backend:latest ghcr.io/allanbikundo/backend:latest
          docker push ghcr.io/allanbikundo/backend:latest
      
      - name: Build and push frontend image
        run: |
          docker build -t ghcr.io/allanbikundo/frontend:latest ./frontend
          docker tag ghcr.io/allanbikundo/frontend:latest ghcr.io/allanbikundo/frontend:latest
          docker push ghcr.io/allanbikundo/frontend:latest

